# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#

# config/database.yml
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # guides.rubyonrails.org
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: ai_api # The username you created in Step 2
  password: "password" #<%= ENV['DATABASE_PASSWORD'] %> # Use an environment variable

development:
  <<: *default
  database: ai_api_development

test:
  <<: *default
  database: ai_api_test
# ... (production environment details typically handled by deployment service)


# Store production database in the storage/ directory, which by default
# is mounted as a persistent Docker volume in config/deploy.yml.
production:
  primary:
    <<: *default
    database: storage/production.sqlite3
  cache:
    <<: *default
    database: storage/production_cache.sqlite3
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: storage/production_queue.sqlite3
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: storage/production_cable.sqlite3
    migrations_paths: db/cable_migrate
